const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILDED: 'FETCH_GENDER_FAILDED',

    FETCH_ROLE_START: 'FETCH_ROLE_START',
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILDED: 'FETCH_ROLE_FAILDED',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILDED: 'CREATE_USER_FAILDED',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILDED: 'EDIT_USER_FAILDED',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILDED: 'DELETE_USER_FAILDED',

    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILDED: 'FETCH_ALL_USERS_FAILDED',

    //category
    CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_FAILDED: 'CREATE_CATEGORY_FAILDED',

    EDIT_CATEGORY_SUCCESS: 'EDIT_CATEGORY_SUCCESS',
    EDIT_CATEGORY_FAILDED: 'EDIT_CATEGORY_FAILDED',

    DELETE_CATEGORY_SUCCESS: 'DELETE_CATEGORY_SUCCESS',
    DELETE_CATEGORY_FAILDED: 'DELETE_CATEGORY_FAILDED',

    FETCH_ALL_CATEGORIES_SUCCESS: 'FETCH_ALL_CATEGORIES_SUCCESS',
    FETCH_ALL_CATEGORIES_FAILDED: 'FETCH_ALL_CATEGORIES_FAILDED',

    FETCH_ALL_CATEGORIES_HOME_SUCCESS: 'FETCH_ALL_CATEGORIES_HOME_SUCCESS',
    FETCH_ALL_CATEGORIES_HOME_FAILDED: 'FETCH_ALL_CATEGORIES_HOME_FAILDED',

    //book
    FETCH_DISCOUNT_SUCCESS: 'FETCH_DISCOUNT_SUCCESS',
    FETCH_DISCOUNT_FAILDED: 'FETCH_DISCOUNT_FAILDED',

    CREATE_BOOK_SUCCESS: 'CREATE_BOOK_SUCCESS',
    CREATE_BOOK_FAILDED: 'CREATE_BOOK_FAILDED',

    EDIT_BOOK_SUCCESS: 'EDIT_BOOK_SUCCESS',
    EDIT_BOOK_FAILDED: 'EDIT_BOOK_FAILDED',

    DELETE_BOOK_SUCCESS: 'DELETE_BOOK_SUCCESS',
    DELETE_BOOK_FAILDED: 'DELETE_BOOK_FAILDED',

    FETCH_ALL_BOOKS_SUCCESS: 'FETCH_ALL_BOOKS_SUCCESS',
    FETCH_ALL_BOOKS_FAILDED: 'FETCH_ALL_BOOKS_FAILDED',

    FETCH_FLASH_SALE_HOME_SUCCESS: 'FETCH_FLASH_SALE_HOME_SUCCESS',
    FETCH_FLASH_SALE_HOME_FAILDED: 'FETCH_FLASH_SALE_HOME_FAILDED',


})

export default actionTypes;